version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --no-audit --no-fund || true; npx live-server --port=3000 --entry-file=index.html --host=0.0.0.0"
    ports:
      - "3000:3000"
